---
## ask user to input ip of onde node
- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: please enter the target host IP
    private: no
                
# add ip address to group
  tasks:
  - add_host:
      name: "{{ target_host }}"
      groups: dynamically_created_hosts
      ansible_user: root
      ansible_ssh_pass: a


## run nodetool status on Single Node
- hosts: dynamically_created_hosts
  tasks:
  - name: get all nodes IP address
    shell: nodetool status | grep UN | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"
    register: hostListString

  - name: add all IP address to group
    add_host: 
      name: '{{ item }}'
      groups: cassandra_dynamically_created_list
      ansible_user: root
      ansible_ssh_pass: a
    with_items: "{{ hostListString.stdout.split('\n') }}"

## iterate over cassandra_dynamically_created_list 
- hosts: cassandra_dynamically_created_list
  serial: 1
  tasks:

  - name: check cassandra uptime
    shell: ps -o etimes= -p $(cat /var/run/cassandra.pid)
    ignore_errors: yes
    register: cassandra_service_uptime
  
  - name: restart cassandra.service 
    systemd: name=cassandra.service state=restarted
    when:
    - cassandra_service_uptime.stdout.strip() | int > 3600

  - name: check port 9042 
    local_action: wait_for host={{ inventory_hostname }} port=9042 timeout=600
