---
- name: edit /etc/hosts/ on spark-master
  lineinfile:
    dest: /etc/hosts
    regexp: '{{inventory_hostname}}'
    line: "{{ inventory_hostname }}    {{ ansible_hostname }}"
  delegate_to: "{{ groups['spark_master'][0] }}"