---
- name: copy spark.service
  template: src=spark-slave.service.j2 dest=/etc/systemd/system/spark-slave.service

- name: start spark.service
  systemd: 
    name: spark-slave.service 
    enabled: yes
    daemon_reload: yes
    state: started